name: ci
on: pull_request

permissions:
  contents: read          # enough to checkout
  checks: write           # allow creating check runs + annotations
  pull-requests: write    # (nice to have for PR-related updates)

jobs:
  verify:
    uses: ConductorOne/github-workflows/.github/workflows/verify.yaml@kans/go-tests
    with:
      ref: ${{ github.ref }}